name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        working-directory: cyclo # Set working directory to the cyclo folder
        run: |
          mvn clean verify

      - name: Run SonarCloud Scan
        working-directory: cyclo # Set working directory to the cyclo folder
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=your_project_key \
            -Dsonar.organization=your_organization_name \
            -Dsonar.host.url=https://sonarcloud.io
